# Generated by Django 3.1.1 on 2020-09-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification',
            new_name='bonus_qualification',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='requirement',
            new_name='technical_requirement',
        ),
    ]
